### ISSUE TITLE
How to use zoom?

### ISSUE THREAD

**Issue by AlexDemure** [Norserium/react-advanced-cropper#1]
I'm trying to implement zoom and zoom buttons but I can't.

There is a zoomImage method, but I can't figure out what values ​​to pass.

Could you write a basic working code?

![image](https://user-images.githubusercontent.com/40522054/166104244-3ed25f23-32be-4f66-a859-fed7cc6dfa05.png)

**Comment by AlexDemure** [comment]
I set step 0.25 but zoom work is not correct.

When I take a step back, he takes a step forward.
![image](https://user-images.githubusercontent.com/40522054/166104575-4a2090f1-0201-4ba3-8790-12331162e566.png)
![image](https://user-images.githubusercontent.com/40522054/166104583-796c8ca0-65c5-485e-8740-3971d193c8b6.png)

**Comment by AlexDemure** [comment]
![image](https://user-images.githubusercontent.com/40522054/166104596-a02b8c61-a961-4039-aa89-8fe5f2805f62.png)

**Comment by AlexDemure** [comment]
currentRef methods don't have method zoom
![image](https://user-images.githubusercontent.com/40522054/166105006-0d2408ce-4d0e-422a-b0fe-eebb78d94336.png)

**Comment by AlexDemure** [comment]
Set step 2 and 0.5

**Comment by Norserium** [comment]
@AlexDemure, there is [the example](https://github.com/Norserium/react-advanced-cropper/blob/master/example/src/components/examples/TransformImageExample.tsx). I will fix the documentation to make it more clear.
