### ISSUE TITLE
Additional icons

### ISSUE THREAD

**Issue by jurica-penjgusic** [Norserium/react-advanced-cropper#3]
We were wondering where can we get additional icons similar to icons that were used in example repo?

**Comment by Norserium** [comment]
@jurica-penjgusic, hello! Which ones? There are many different icons (at the main page, recipes and etc.). Generally, it's a mix icons from different sources and mine own icons.

**Comment by jurica-penjgusic** [comment]
Tnx for quick response, probably edit and upload image.

**Comment by Norserium** [comment]
@jurica-penjgusic, well, I don't understand your last phrase. Do you need the edit and upload images that similar to some sort of icons? Which one?

**Comment by jurica-penjgusic** [comment]
It would be great if you hav, "Upload from computer icon", "Edit icon".

**Comment by Norserium** [comment]
![image](https://user-images.githubusercontent.com/9862719/172023943-ecbe4648-abd0-4898-98e7-20270cddda33.png)
Currently I have the following icons, that was prepared for the upcoming example.

**Comment by Norserium** [comment]
@jurica-penjgusic, what does edit icon mean in your context?

**Comment by Norserium** [comment]
@jurica-penjgusic, could you take some screenshots of LinkedIn? It would be helpful for me. Do you want to implement the similar functional with filters?

**Comment by Norserium** [comment]
> Hi, this example that will be uploaded is awesome!!

Actually, it's not the new example. The new one is better. I just move the download and upload buttons to the example at the main page for the screenshot.

**Comment by jurica-penjgusic** [comment]
Yep, the example that will go with. ext release is reallly good! So we decided to go on that aproach. Looking forward to see it in action!

**Comment by Norserium** [comment]
@jurica-penjgusic, I assume there was a little misunderstanding.

I've said, that I created icons for the upcoming example. [This example](https://norserium.github.io/react-advanced-cropper/docs/tutorials/image-editor) is published now.

I have no plans to add them to the examples of the cropper wizard like I showed on the screenshot above  for the demonstration purpose, but you can use that icons in your own cropper: [\<DownloadIcon/>](https://github.com/Norserium/react-advanced-cropper/blob/master/example/src/components/icons/DownloadIcon.tsx), [\<UploadIcon/>](https://github.com/Norserium/react-advanced-cropper/blob/master/example/src/components/icons/UploadIcon.tsx).

**Comment by jurica-penjgusic** [comment]
Oh, it’s already created, nice work!
Tnx for the icons.
Keep up with the good work!!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Norserium** [comment]
@jurica-penjgusic, you are welcome!
